# Generated by Django 4.0.8 on 2022-12-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
